### ISSUE TITLE
pip install fails on v0.1.1, no requirements-dev.txt

### ISSUE THREAD

**Issue by perrygeo** [h2non/paco#15]
```
$ pip install paco
Collecting paco
  Downloading paco-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c3/sjz4d98x1qvg040bty83_8940000gn/T/pip-build-robc7d_6/paco/setup.py", line 22, in <module>
        with open('requirements-dev.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements-dev.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/c3/sjz4d98x1qvg040bty83_8940000gn/T/pip-build-robc7d_6/paco/
```

I'd suggest building with `bdist_wheel` to get python 3 wheels which don't require running setup code code on install. And/or you can include the requirements file in your manifest ala http://stackoverflow.com/a/1857436/519385

**Comment by h2non** [comment]
This should be fixed in `v0.1.2`. Try installing it again. 
I'm sorry for the inconvenience.
