### ISSUE TITLE
Unexpected `paco.map` behaviour

### ISSUE THREAD

**Issue by Gr1N** [h2non/paco#25]
Hi!

Today, I ran into an unexpected behavior of `paco.map` function. 
But first let's see some built-in `map` examples:
```
In [1]: def foo(bar): return bar ** bar

In [2]: list(map(foo, [1, 2, 3]))
Out[2]: [1, 4, 27]

In [3]: list(map(foo, []))
Out[3]: []
```
Everything works as expected.

And now let's try same examples, but using `paco`:
```In [1]: import paco

In [2]: async def foo(bar): return bar ** bar

In [3]: paco.run(paco.map(foo, [1, 2, 3]))
Out[3]: [1, 4, 27]
```
Okay, works in same way, but:
```
In [4]: paco.run(paco.map(foo, []))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-85707eefeb82> in <module>()
----> 1 paco.run(paco.map(foo, []))

/Users/nikitagrishko/.virtualenvs/tmp-f9150bf5d248f905/lib/python3.5/site-packages/paco/run.py in run(coro, loop)
     15     """
     16     loop = loop or asyncio.get_event_loop()
---> 17     return loop.run_until_complete(coro)

/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py in run_until_complete(self, future)
    385             raise RuntimeError('Event loop stopped before Future completed.')
    386
--> 387         return future.result()
    388
    389     def stop(self):

/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py in result(self)
    272             self._tb_logger = None
    273         if self._exception is not None:
--> 274             raise self._exception
    275         return self._result
    276

/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/Users/nikitagrishko/.virtualenvs/tmp-f9150bf5d248f905/lib/python3.5/site-packages/paco/map.py in map(coro, iterable, limit, loop, timeout, return_exceptions, *args, **kw)
     50     return (yield from each(coro, iterable,
     51                             limit=limit, loop=loop,
---> 52                             timeout=timeout, collect=True))

/Users/nikitagrishko/.virtualenvs/tmp-f9150bf5d248f905/lib/python3.5/site-packages/paco/each.py in each(coro, iterable, limit, loop, collect, timeout, return_exceptions, *args, **kw)
     84
     85     # Wait until all the coroutines finishes
---> 86     yield from pool.run(timeout=timeout)
     87
     88     # Returns list of mapped results in order

/Users/nikitagrishko/.virtualenvs/tmp-f9150bf5d248f905/lib/python3.5/site-packages/paco/concurrent.py in run(self, timeout, return_exceptions, return_when)
    304         # Check we have coroutines to schedule
    305         if len(self.pool) == 0:
--> 306             raise ValueError('no coroutines to schedule')
    307
    308         # Set executor state to running

ValueError: no coroutines to schedule
```
Ops... To my mind it's a bug, because it's an unexpected behavior for functional programming and we need to fix it. 

@h2non, what do you think?

**Comment by h2non** [comment]
In another context, I would probably agree, but the initial design `paco` tends to leverage `asyncio` built-in package.

Consider this scenario:
```python
import paco
import asyncio

paco.run(asyncio.wait([]))
```

Which raises a `ValueError`:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/h2non/.pyenv/versions/3.5.2/lib/python3.5/site-packages/paco/run.py", line 17, in run
    return loop.run_until_complete(coro)
  File "/Users/h2non/.pyenv/versions/3.5.2/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/Users/h2non/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Users/h2non/.pyenv/versions/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Users/h2non/.pyenv/versions/3.5.2/lib/python3.5/asyncio/tasks.py", line 338, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.
```

My position is that failing with an exception is the most predictable and idiomatic behavior based on how `asyncio` primitives behaves too. 

If you don't have a set of coroutines to schedule, there's probably a bug or unexpected situation in your code and you must be aware of that, so `paco`, as well as `asyncio`, tries to help and inform the developer.

Behavioral discussions tend to be prone to bias based on people preferences and precedents. 
In cases of ambiguity, I tend to bet for the most predictable and robust behavior that fits better for the majority of the scenarios.

**Comment by Gr1N** [comment]
Got your point and I partially agree with you, explicit is better than implicit.
But from user point of view I'm not interested in package implementation, I'm looking into documentation and see that package implemented in functional style (`map`, `each`, `partial`, etc.) and I want to use your package to speedup some parts of my code, e.g.:
```
In [1]: def foo(l):
   ...:     l = map(lambda i: i ** 2, l)
   ...:     l = filter(lambda i: i > 10, l)
   ...:     l = map(lambda i: i ** i, l)
   ...:     return list(l)
   ...:

In [2]: foo([10, 11, 12])
Out[3]: [200, 242, 288]

In [3]: foo([1, 2, 3])
Out[3]: []
```
And if I want to use `paco`, I just want to update my code to:
```
In [1]: import paco

In [2]: async def foo(l):
   ...:     l = await paco.map(paco.wraps(lambda i: i ** 2), l)
   ...:     l = list(filter(lambda i: i > 10, l))
   ...:     l = await paco.map(paco.wraps(lambda i: i + i), l)
   ...:     return l
   ...:

In [3]: paco.run(foo([10, 11, 12]))
Out[3]: [200, 242, 288]
```
But because of current implementation I can't run rewritten code with `[1, 2, 3]` and I need to rewrite my code in another way:
```
In [5]: async def foo(l):
   ...:     if not l: return l
   ...:     l = await paco.map(paco.wraps(lambda i: i ** 2), l)
   ...:     l = list(filter(lambda i: i > 10, l))
   ...:     if not l: return l
   ...:     l = await paco.map(paco.wraps(lambda i: i + i), l)
   ...:     return l
   ...:

In [6]: paco.run(foo([1, 2, 3]))
Out[6]: []

In [7]: paco.run(foo([10, 11, 12]))
Out[7]: [200, 242, 288]
```
Now it works as expected, but I don't want to check if iterable is empty or not.

@h2non, I think that if you want to stay with current behavior you need to update documentation (add attentions for users which want to use your package like I described) or think on how to change current behavior. But maybe I'm wrong and there are another way to solve this.

**Comment by h2non** [comment]
I was thinking about this and there's certainly a scenario where introducing your proposal is particularly convenient, such as composing multiple functors.

Consider the following example using pipeline style via operator overloading supported in `paco`:
```python
await (iterable
            | paco.filter(filterer)
            | paco.map(mapper)
            | paco.dropwhile(drop)
            | paco.reduce(reducer, initializer=0))
```

There are actually multiple ways to support this in `paco`, but I can reconsider your proposal.
My idea would be supporting it only for functional iterables, such as `map`, `filter`, `reduce`...

**Comment by h2non** [comment]
I can come with a solid solution tomorrow.

**Comment by Gr1N** [comment]
Nice to hear, thanks.

**Comment by h2non** [comment]
This enhancement was introduced in paco v0.1.5. 

See commits for more details:
https://github.com/h2non/paco/commit/4528783d41d7700c66992d167d8fa24ee86fccf4
https://github.com/h2non/paco/commit/4528783d41d7700c66992d167d8fa24ee86fccf4

You can upgrade `paco` running:
```bash
pip install --upgrade paco
```

Let me know if there's some trouble. Closing issue for now.

**Comment by Gr1N** [comment]
Great work, thank you!
